import React from 'react';
import { useAuth } from '../context/AuthContext';
import { FileText, Printer, ExternalLink, ShieldCheck } from 'lucide-react';
import { api } from '../services/api';

interface ReportsPageProps {
  onOpenReportModal: () => void;
}

export const ReportsPage: React.FC<ReportsPageProps> = ({ onOpenReportModal }) => {
  const { currentMSME } = useAuth();

  if (!currentMSME) return <div className="p-8 text-slate-500">Loading Reports...</div>;

  const reportUrl = api.getReportDownloadUrl(currentMSME.id);

  return (
    <div className="space-y-6">
      {/* Page Header */}
      <div className="border-b border-[#ffffff10] pb-5">
        <div className="flex items-center gap-2 mb-1">
          <span className="h-[1px] w-8 bg-stone-600"></span>
          <span className="text-[10px] font-light uppercase tracking-[0.3em] text-stone-400">FINANCIAL INTELLIGENCE DOSSIER</span>
        </div>
        <h1 className="text-2xl sm:text-3xl font-serif italic text-white font-normal">Intelligence Reports & Export</h1>
        <p className="text-xs text-stone-400 font-light mt-1">
          Generate, preview, and print comprehensive credit health dossiers for {currentMSME.companyName}
        </p>
      </div>

      {/* Main Report Card */}
      <div className="bg-[#121212] p-6 border border-[#ffffff15] space-y-6">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-[#ffffff10] pb-5">
          <div className="flex items-center space-x-3">
            <div className="w-10 h-10 bg-[#1A1A1A] border border-[#ffffff15] flex items-center justify-center text-amber-300">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <h3 className="font-serif font-medium text-white text-base">{currentMSME.companyName} — Credit Dossier</h3>
              <p className="text-xs text-stone-400 font-light">VyapaarTrust Score {currentMSME.analysis.trustScore}/100 • {currentMSME.analysis.riskLevel}</p>
            </div>
          </div>

          <div className="flex items-center space-x-3">
            <a
              href={reportUrl}
              target="_blank"
              rel="noreferrer"
              className="bg-[#161616] hover:bg-[#202020] text-stone-300 text-xs font-light tracking-wider uppercase px-4 py-2.5 border border-[#ffffff15] transition flex items-center space-x-1.5"
            >
              <ExternalLink className="w-3.5 h-3.5" />
              <span>HTML Dossier</span>
            </a>

            <button
              onClick={onOpenReportModal}
              className="border border-[#ffffff] text-white hover:bg-white hover:text-black text-xs font-light tracking-[0.2em] uppercase px-5 py-2.5 transition-colors flex items-center space-x-2"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Preview & Export PDF</span>
            </button>
          </div>
        </div>

        {/* Report Overview Teaser */}
        <div className="bg-[#1A1A1A] p-5 border border-[#ffffff10] space-y-3 text-xs text-stone-300 font-light">
          <div className="font-serif font-normal text-white text-sm">Included Intelligence Dossier Sections:</div>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-stone-400">
            <div>✓ Business Overview & GSTIN Profile</div>
            <div>✓ VyapaarTrust Score & Risk Classification</div>
            <div>✓ 5 Financial Health Component Pillars</div>
            <div>✓ SHAP Feature Contributions</div>
            <div>✓ Dynamic AI Business Interpretation Text</div>
            <div>✓ Actionable Credit Readiness Recommendations</div>
          </div>
        </div>

        <div className="flex items-center space-x-2 text-[10px] text-amber-300/80 bg-amber-950/40 p-3 border border-amber-800/60 font-light">
          <ShieldCheck className="w-4 h-4 text-amber-300 shrink-0" />
          <span>
            <strong className="text-white font-normal uppercase tracking-wider">Disclaimer:</strong> This report is generated by a prototype decision-support system using demonstration data connectors. It does not constitute an official loan guarantee or credit approval.
          </span>
        </div>
      </div>
    </div>
  );
};
