import React from 'react';
import { MSMEProfile } from '../types';
import { api } from '../services/api';
import { Download, Printer, X, FileText, ExternalLink } from 'lucide-react';

interface ReportModalProps {
  msme: MSMEProfile;
  isOpen: boolean;
  onClose: () => void;
}

export const ReportModal: React.FC<ReportModalProps> = ({ msme, isOpen, onClose }) => {
  if (!isOpen) return null;

  const reportUrl = api.getReportDownloadUrl(msme.id);

  const handlePrint = () => {
    const win = window.open(reportUrl, '_blank');
    if (win) {
      win.focus();
    }
  };

  return (
    <div className="fixed inset-0 z-50 bg-black/80 backdrop-blur-xs flex items-center justify-center p-4">
      <div className="bg-[#121212] max-w-4xl w-full border border-[#ffffff20] shadow-2xl overflow-hidden h-[85vh] flex flex-col">
        {/* Header */}
        <div className="bg-[#0A0A0A] text-white p-4 sm:p-6 flex items-center justify-between border-b border-[#ffffff15] shrink-0">
          <div className="flex items-center space-x-3">
            <div className="w-10 h-10 bg-[#1A1A1A] border border-[#ffffff15] flex items-center justify-center text-amber-300">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <h3 className="font-serif font-medium text-base text-white">{msme.companyName} — Financial Dossier</h3>
              <p className="text-xs text-stone-400 font-light">VyapaarTrust Score {msme.analysis.trustScore}/100 • {msme.analysis.riskLevel}</p>
            </div>
          </div>

          <div className="flex items-center space-x-2">
            <button
              onClick={handlePrint}
              className="flex items-center space-x-1.5 border border-[#ffffff] text-white hover:bg-white hover:text-black text-xs font-light tracking-[0.2em] uppercase px-3 py-2 transition-colors"
            >
              <Printer className="w-3.5 h-3.5" />
              <span className="hidden sm:inline">Print / Save PDF</span>
            </button>
            <a
              href={reportUrl}
              target="_blank"
              rel="noreferrer"
              className="flex items-center space-x-1.5 bg-[#161616] hover:bg-[#202020] text-stone-300 text-xs font-light tracking-wider uppercase px-3 py-2 border border-[#ffffff15] transition"
            >
              <ExternalLink className="w-3.5 h-3.5" />
              <span className="hidden sm:inline">Open HTML</span>
            </a>
            <button onClick={onClose} className="text-stone-400 hover:text-white p-2">
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Embedded Report Frame */}
        <div className="flex-1 bg-black overflow-hidden relative">
          <iframe
            src={reportUrl}
            title="Financial Intelligence Report Preview"
            className="w-full h-full border-none"
          />
        </div>

        {/* Footer Disclaimer */}
        <div className="bg-[#0A0A0A] border-t border-[#ffffff15] p-3 px-6 text-[10px] text-stone-400 font-light flex items-center justify-between shrink-0">
          <span>
            <strong className="text-white font-normal uppercase tracking-wider">Disclaimer:</strong> Generated by VyapaarTrust decision-support system. Does not constitute official bank underwriting.
          </span>
          <span className="font-mono text-stone-500">v1.0</span>
        </div>
      </div>
    </div>
  );
};
